2023-02-08 13:14:55,063 INFO    MainThread:18328 [wandb_setup.py:_flush():68] Configure stats pid to 18328
2023-02-08 13:14:55,063 INFO    MainThread:18328 [wandb_setup.py:_flush():68] Loading settings from C:\Users\user\.config\wandb\settings
2023-02-08 13:14:55,063 INFO    MainThread:18328 [wandb_setup.py:_flush():68] Loading settings from C:\Users\user\Project-Cars\model\Pretrained\wandb\settings
2023-02-08 13:14:55,063 INFO    MainThread:18328 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-08 13:14:55,063 INFO    MainThread:18328 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'model\\Pretrained\\train.py', 'program': 'C:\\Users\\user\\Project-Cars\\model\\Pretrained\\train.py'}
2023-02-08 13:14:55,063 INFO    MainThread:18328 [wandb_init.py:_log_setup():492] Logging user logs to C:\Users\user\Project-Cars\model\Pretrained\wandb\run-20230208_131455-do94e436\logs\debug.log
2023-02-08 13:14:55,063 INFO    MainThread:18328 [wandb_init.py:_log_setup():493] Logging internal logs to C:\Users\user\Project-Cars\model\Pretrained\wandb\run-20230208_131455-do94e436\logs\debug-internal.log
2023-02-08 13:14:55,063 INFO    MainThread:18328 [wandb_init.py:init():532] calling init triggers
2023-02-08 13:14:55,063 INFO    MainThread:18328 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {'batch_size': 64, 'learning_rate': 1e-05, 'weight_decay': 0.01, 'epochs': 2, 'zero_init_residual': False, 'num_classes': 196}
2023-02-08 13:14:55,063 INFO    MainThread:18328 [wandb_init.py:init():588] starting backend
2023-02-08 13:14:55,063 INFO    MainThread:18328 [wandb_init.py:init():592] setting up manager
2023-02-08 13:14:55,063 INFO    MainThread:18328 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-02-08 13:14:55,078 INFO    MainThread:18328 [wandb_init.py:init():599] backend started and connected
2023-02-08 13:14:55,078 INFO    MainThread:18328 [wandb_init.py:init():687] updated telemetry
2023-02-08 13:14:55,141 INFO    MainThread:18328 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-02-08 13:15:00,172 WARNING MsgRouterThr:18328 [router.py:message_loop():77] message_loop has been closed
2023-02-08 13:15:00,188 ERROR   MainThread:18328 [wandb_init.py:init():1160] error
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_init.py", line 1133, in init
    run = wi.init()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_init.py", line 730, in init
    result = run_init_handle.wait(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\lib\mailbox.py", line 271, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
